import random
import time


class signature_General_settings():
    def __init__(self,driver):

        self.driver=driver
        self.huluhb_icon = "/html/body/app-root/app-layout/div/app-topbar/header/div/div[1]/div/a[2]/span[1]/img"  # hulub icon click to land on dasboard
        self.settings_icon = "/html/body/app-root/app-layout/div/app-topbar/header/div/div[2]/div[5]/button"
        self.general_tab = "/html/body/app-root/app-layout/div/div/div/app-settings/div/div/div/div[1]/div/ul/li[1]/a/div"
        self.signature_card="/html/body/app-root/app-layout/div/div/div/app-settings/div/div/div/div[2]/div/div/div/div/div[2]/div[1]/div[2]/div[3]/div/div"
        self.signature_header_text_box="/html/body/app-root/app-layout/div/div/div/app-signature/div/div/div[2]/div/div/div/ckeditor[1]/div[2]/p"
        self.signature_footer_text_box="/html/body/app-root/app-layout/div/div/div/app-signature/div/div/div[2]/div/div/div/ckeditor[2]/div[2]"
        self.save_button_of_signature="/html/body/app-root/app-layout/div/div/div/app-signature/div/div/div[2]/div/div/div/button"



    def signature_method(self):
        fe=self.driver.find_element_by_xpath
        fe(self.huluhb_icon).click()
        fe(self.settings_icon).click()
        fe(self.general_tab).click()
        fe(self.signature_card).click()
        rand=random.randint(0,96325874154)

        header="Signature generated by automation script--Header"+str(rand)
        fe(self.signature_header_text_box).send_keys(header)
        fe(self.signature_footer_text_box).send_keys("Signature generated by automation script--Footer",rand)
        fe(self.save_button_of_signature).click()
        time.sleep(3)
        print("Signature Created")

        fe("/html/body/app-root/app-layout/div/div/div/app-signature/div/div/div[1]/div[1]/div/input").send_keys(header)

        fe("/html/body/app-root/app-layout/div/div/div/app-signature/div/div/div[1]/div[2]/div[1]/div/div/div/div[1]/div/div/span[3]/i").click()##eye icon of signature

        header_text_in_popup=fe("/html/body/ngb-modal-window/div/div/app-signature-preview/div[2]/div/span[1]/p").text

        if header == header_text_in_popup:
            print("Signature created and appeared in the view popup as well")

        else:
            print("PRINT signature are different")

        time.sleep(2)
        fe("/html/body/ngb-modal-window/div/div/app-signature-preview/div[1]/button").click()#close icon of popup

